### PR TITLE
Upgrade bitstyles to 6.0.0

### PR DESCRIPTION
**Pull request by angelikatyborska**
Based on top of https://github.com/bitcrowd/bitstyles_phoenix/pull/125

Resolves https://github.com/bitcrowd/bitstyles_phoenix/issues/110 https://github.com/bitcrowd/bitstyles_phoenix/issues/108 https://github.com/bitcrowd/bitstyles_phoenix/issues/109

### CODE REVIEW

**Comment by angelikatyborska** [comment]
@andreasknoepfle I ran into a surprise: the class replacements from the classnames helper do not chain... For example, there was this chain of renaming:

```
u-fg-grayscale-dark-2 (6.0.0) -> u-fg-text-darker (5.0.0) -> u-fg-gray-50 (4.3.0)
```

If I render a component that uses the class `u-fg-grayscale-dark-2`, and I render it for v4.3.0, it ends up with the class `u-fg-text-darker` instead of ` u-fg-gray-50` because replacements are applied backwards 🤔 (first from 5.0.0 -> 4.3.0, then from 6.0.0 -> 5.0.0).

**Comment by angelikatyborska** [comment]
> I ran into a surprise: the class replacements from the classnames helper do not chain... For example, there was this chain of renaming:


Will be resolved by merging https://github.com/bitcrowd/bitstyles_phoenix/pull/134 first

**Comment by angelikatyborska** [comment]
I'm pretty confident of those changes because we've been using them in the IDA backend with no hiccups

**Review by andreasknoepfle — APPROVED** [review]
Changes look awesome. The only thing missing for me is an entry to the CHANGELOG.md

**Pull request merged**
